# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\jumen\Documents\Codes\python\convertQT\graphui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(339, 327)
        MainWindow.setStyleSheet("background-color: rgb(31, 31, 31);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frameC = QtWidgets.QFrame(self.centralwidget)
        self.frameC.setStyleSheet("color: rgb(255, 255, 255);")
        self.frameC.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameC.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameC.setObjectName("frameC")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameC)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textC = QtWidgets.QLabel(self.frameC)
        self.textC.setObjectName("textC")
        self.horizontalLayout.addWidget(self.textC, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.frameC, 2, 4, 1, 1)
        self.xquadrado = QtWidgets.QLabel(self.centralwidget)
        self.xquadrado.setStyleSheet("color: rgb(255, 255, 255);")
        self.xquadrado.setObjectName("xquadrado")
        self.gridLayout.addWidget(self.xquadrado, 3, 1, 1, 1)
        self.boxB = QtWidgets.QLineEdit(self.centralwidget)
        self.boxB.setStyleSheet("background-color: rgb(89, 89, 89);")
        self.boxB.setObjectName("boxB")
        self.gridLayout.addWidget(self.boxB, 3, 2, 1, 1)
        self.ok = QtWidgets.QPushButton(self.centralwidget)
        self.ok.setMinimumSize(QtCore.QSize(60, 20))
        self.ok.setStyleSheet("QPushButton{\n"
"background-color: rgb(104,171,75); \n"
"color: rgb(0,0,0);\n"
"border-radius:5px;\n"
"}QPushButton::hover{\n"
"background-color: rgb(104,171,75); \n"
"color: rgb(255,255,255);\n"
"border-radius:5px;\n"
"}QPushButton::pressed{\n"
"background-color: rgb(154,231,125); \n"
"color: rgb(255,255,255);\n"
"border-radius:5px;\n"
"}")
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 3, 5, 1, 1)
        self.xmais = QtWidgets.QLabel(self.centralwidget)
        self.xmais.setStyleSheet("color: rgb(255, 255, 255);")
        self.xmais.setObjectName("xmais")
        self.gridLayout.addWidget(self.xmais, 3, 3, 1, 1)
        self.boxC = QtWidgets.QLineEdit(self.centralwidget)
        self.boxC.setStyleSheet("background-color: rgb(89, 89, 89);")
        self.boxC.setObjectName("boxC")
        self.gridLayout.addWidget(self.boxC, 3, 4, 1, 1)
        self.frameB = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameB.sizePolicy().hasHeightForWidth())
        self.frameB.setSizePolicy(sizePolicy)
        self.frameB.setStyleSheet("color: rgb(255, 255, 255);")
        self.frameB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameB.setObjectName("frameB")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameB)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textB = QtWidgets.QLabel(self.frameB)
        self.textB.setObjectName("textB")
        self.horizontalLayout_2.addWidget(self.textB, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.frameB, 2, 2, 1, 1)
        self.frameA = QtWidgets.QFrame(self.centralwidget)
        self.frameA.setStyleSheet("color: rgb(255, 255, 255);")
        self.frameA.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameA.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameA.setObjectName("frameA")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frameA)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textA = QtWidgets.QLabel(self.frameA)
        self.textA.setObjectName("textA")
        self.horizontalLayout_3.addWidget(self.textA, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.frameA, 2, 0, 1, 1)
        self.tela = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.tela.sizePolicy().hasHeightForWidth())
        self.tela.setSizePolicy(sizePolicy)
        self.tela.setMinimumSize(QtCore.QSize(300, 200))
        self.tela.setSizeIncrement(QtCore.QSize(0, 0))
        self.tela.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tela.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tela.setObjectName("tela")
        self.gridLayout.addWidget(self.tela, 0, 0, 1, 6)
        self.boxA = QtWidgets.QLineEdit(self.centralwidget)
        self.boxA.setStyleSheet("background-color: rgb(89, 89, 89);")
        self.boxA.setObjectName("boxA")
        self.gridLayout.addWidget(self.boxA, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 339, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.boxA, self.boxB)
        MainWindow.setTabOrder(self.boxB, self.boxC)
        MainWindow.setTabOrder(self.boxC, self.ok)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textC.setText(_translate("MainWindow", "C"))
        self.xquadrado.setText(_translate("MainWindow", "x² +"))
        self.ok.setText(_translate("MainWindow", "Ok"))
        self.xmais.setText(_translate("MainWindow", "x + "))
        self.textB.setText(_translate("MainWindow", "B"))
        self.textA.setText(_translate("MainWindow", "A"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
