# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jumen\Documents\Codes\python\AddSay\Qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(781, 470)
        MainWindow.setStyleSheet("background-color: rgb(79, 79, 79);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameFundo = QtWidgets.QFrame(self.centralwidget)
        self.frameFundo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFundo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFundo.setObjectName("frameFundo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameFundo)
        self.verticalLayout_2.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameTextCima = QtWidgets.QFrame(self.frameFundo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameTextCima.sizePolicy().hasHeightForWidth())
        self.frameTextCima.setSizePolicy(sizePolicy)
        self.frameTextCima.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTextCima.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTextCima.setObjectName("frameTextCima")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameTextCima)
        self.horizontalLayout_2.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelA = QtWidgets.QLabel(self.frameTextCima)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelA.sizePolicy().hasHeightForWidth())
        self.labelA.setSizePolicy(sizePolicy)
        self.labelA.setMaximumSize(QtCore.QSize(55, 16777215))
        self.labelA.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.labelA.setObjectName("labelA")
        self.horizontalLayout_2.addWidget(self.labelA)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.labelS = QtWidgets.QLabel(self.frameTextCima)
        self.labelS.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelS.setObjectName("labelS")
        self.horizontalLayout_2.addWidget(self.labelS)
        self.pushButtonEdit = QtWidgets.QPushButton(self.frameTextCima)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonEdit.sizePolicy().hasHeightForWidth())
        self.pushButtonEdit.setSizePolicy(sizePolicy)
        self.pushButtonEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButtonEdit.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 0, 0); \n"
"color: rgb(0,0,0);\n"
"border-radius:5px;\n"
"}QPushButton::hover{\n"
"background-color: rgb(170, 0, 0); \n"
"color: rgb(255,255,255);\n"
"border-radius:5px;\n"
"}QPushButton::pressed{\n"
"background-color: rgb(209, 100, 100); \n"
"color: rgb(255,255,255);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"")
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.horizontalLayout_2.addWidget(self.pushButtonEdit)
        self.verticalLayout_2.addWidget(self.frameTextCima)
        self.frameAdd = QtWidgets.QFrame(self.frameFundo)
        self.frameAdd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAdd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAdd.setObjectName("frameAdd")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameAdd)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditA = QtWidgets.QLineEdit(self.frameAdd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditA.sizePolicy().hasHeightForWidth())
        self.lineEditA.setSizePolicy(sizePolicy)
        self.lineEditA.setMaximumSize(QtCore.QSize(55, 16777215))
        self.lineEditA.setObjectName("lineEditA")
        self.horizontalLayout.addWidget(self.lineEditA)
        self.lineEditS = QtWidgets.QLineEdit(self.frameAdd)
        self.lineEditS.setObjectName("lineEditS")
        self.horizontalLayout.addWidget(self.lineEditS)
        self.pushButtonOk = QtWidgets.QPushButton(self.frameAdd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOk.sizePolicy().hasHeightForWidth())
        self.pushButtonOk.setSizePolicy(sizePolicy)
        self.pushButtonOk.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButtonOk.setStyleSheet("QPushButton{\n"
"background-color: rgb(104,171,75); \n"
"color: rgb(0,0,0);\n"
"border-radius:5px;\n"
"}QPushButton::hover{\n"
"background-color: rgb(104,171,75); \n"
"color: rgb(255,255,255);\n"
"border-radius:5px;\n"
"}QPushButton::pressed{\n"
"background-color: rgb(154,231,125); \n"
"color: rgb(255,255,255);\n"
"border-radius:5px;\n"
"}")
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.horizontalLayout.addWidget(self.pushButtonOk)
        self.verticalLayout_2.addWidget(self.frameAdd)
        self.Tabela = QtWidgets.QTableWidget(self.frameFundo)
        self.Tabela.setStyleSheet("color: rgb(255, 255, 255);")
        self.Tabela.setObjectName("Tabela")
        self.Tabela.setColumnCount(2)
        self.Tabela.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setItem(0, 1, item)
        self.Tabela.horizontalHeader().setVisible(False)
        self.Tabela.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.Tabela)
        self.frame = QtWidgets.QFrame(self.frameFundo)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frameFundo)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Say\'s - By Ehpsker"))
        self.labelA.setText(_translate("MainWindow", "Atalho"))
        self.labelS.setText(_translate("MainWindow", "Say"))
        self.pushButtonEdit.setText(_translate("MainWindow", "Remove"))
        self.pushButtonOk.setText(_translate("MainWindow", "Add"))
        item = self.Tabela.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Tabela.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Atalho"))
        item = self.Tabela.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Say"))
        __sortingEnabled = self.Tabela.isSortingEnabled()
        self.Tabela.setSortingEnabled(False)
        item = self.Tabela.item(0, 0)
        item.setText(_translate("MainWindow", "OI"))
        item = self.Tabela.item(0, 1)
        item.setText(_translate("MainWindow", "Amigo"))
        self.Tabela.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Caminho"))
