# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora-desing.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 535)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(31, 31, 31);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bponto = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.bponto.sizePolicy().hasHeightForWidth())
        self.bponto.setSizePolicy(sizePolicy)
        self.bponto.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bponto.setFont(font)
        self.bponto.setStyleSheet("background-color: rgb(52, 52, 52);\n"
                                  "color: rgb(255, 255, 255);")
        self.bponto.setObjectName("bponto")
        self.gridLayout.addWidget(self.bponto, 5, 2, 1, 1)
        self.bmenos = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.bmenos.sizePolicy().hasHeightForWidth())
        self.bmenos.setSizePolicy(sizePolicy)
        self.bmenos.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bmenos.setFont(font)
        self.bmenos.setStyleSheet("background-color: rgb(52, 52, 52);\n"
                                  "color: rgb(255, 255, 255);")
        self.bmenos.setObjectName("bmenos")
        self.gridLayout.addWidget(self.bmenos, 3, 3, 1, 1)
        self.b6 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b6.sizePolicy().hasHeightForWidth())
        self.b6.setSizePolicy(sizePolicy)
        self.b6.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b6.setFont(font)
        self.b6.setStyleSheet("background-color: rgb(52, 52, 52);\n"
                              "color: rgb(255, 255, 255);")
        self.b6.setObjectName("b6")
        self.gridLayout.addWidget(self.b6, 3, 2, 1, 1)
        self.bigual = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.bigual.sizePolicy().hasHeightForWidth())
        self.bigual.setSizePolicy(sizePolicy)
        self.bigual.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bigual.setFont(font)
        self.bigual.setStyleSheet("background-color: rgb(3, 111, 196);")
        self.bigual.setObjectName("bigual")
        self.gridLayout.addWidget(self.bigual, 5, 3, 1, 1)
        self.b2 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b2.sizePolicy().hasHeightForWidth())
        self.b2.setSizePolicy(sizePolicy)
        self.b2.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setStyleSheet("background-color: rgb(52, 52, 52);\n"
                              "color: rgb(255, 255, 255);")
        self.b2.setObjectName("b2")
        self.gridLayout.addWidget(self.b2, 4, 1, 1, 1)
        self.bdiv = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.bdiv.sizePolicy().hasHeightForWidth())
        self.bdiv.setSizePolicy(sizePolicy)
        self.bdiv.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bdiv.setFont(font)
        self.bdiv.setStyleSheet("background-color: rgb(52, 52, 52);\n"
                                "color: rgb(255, 255, 255);")
        self.bdiv.setObjectName("bdiv")
        self.gridLayout.addWidget(self.bdiv, 1, 3, 1, 1)
        self.b1 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b1.sizePolicy().hasHeightForWidth())
        self.b1.setSizePolicy(sizePolicy)
        self.b1.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setStyleSheet("background-color: rgb(52, 52, 52);\n"
                              "color: rgb(255, 255, 255);")
        self.b1.setObjectName("b1")
        self.gridLayout.addWidget(self.b1, 4, 0, 1, 1)
        self.b5 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b5.sizePolicy().hasHeightForWidth())
        self.b5.setSizePolicy(sizePolicy)
        self.b5.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b5.setFont(font)
        self.b5.setStyleSheet("background-color: rgb(52, 52, 52);\n"
                              "color: rgb(255, 255, 255);")
        self.b5.setObjectName("b5")
        self.gridLayout.addWidget(self.b5, 3, 1, 1, 1)
        self.b9 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b9.sizePolicy().hasHeightForWidth())
        self.b9.setSizePolicy(sizePolicy)
        self.b9.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b9.setFont(font)
        self.b9.setStyleSheet("background-color: rgb(52, 52, 52);\n"
                              "color: rgb(255, 255, 255);")
        self.b9.setObjectName("b9")
        self.gridLayout.addWidget(self.b9, 2, 2, 1, 1)
        self.b7 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b7.sizePolicy().hasHeightForWidth())
        self.b7.setSizePolicy(sizePolicy)
        self.b7.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b7.setFont(font)
        self.b7.setStyleSheet("background-color: rgb(52, 52, 52);\n"
                              "color: rgb(255, 255, 255);")
        self.b7.setObjectName("b7")
        self.gridLayout.addWidget(self.b7, 2, 0, 1, 1)
        self.b0 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b0.sizePolicy().hasHeightForWidth())
        self.b0.setSizePolicy(sizePolicy)
        self.b0.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b0.setFont(font)
        self.b0.setStyleSheet("background-color: rgb(52, 52, 52);\n"
                              "color: rgb(255, 255, 255);")
        self.b0.setObjectName("b0")
        self.gridLayout.addWidget(self.b0, 5, 1, 1, 1)
        self.b4 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b4.sizePolicy().hasHeightForWidth())
        self.b4.setSizePolicy(sizePolicy)
        self.b4.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setStyleSheet("background-color: rgb(52, 52, 52);\n"
                              "color: rgb(255, 255, 255);")
        self.b4.setObjectName("b4")
        self.gridLayout.addWidget(self.b4, 3, 0, 1, 1)
        self.b3 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b3.sizePolicy().hasHeightForWidth())
        self.b3.setSizePolicy(sizePolicy)
        self.b3.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setStyleSheet("background-color: rgb(52, 52, 52);\n"
                              "color: rgb(255, 255, 255);")
        self.b3.setObjectName("b3")
        self.gridLayout.addWidget(self.b3, 4, 2, 1, 1)
        self.bmais = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.bmais.sizePolicy().hasHeightForWidth())
        self.bmais.setSizePolicy(sizePolicy)
        self.bmais.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bmais.setFont(font)
        self.bmais.setStyleSheet("background-color: rgb(52, 52, 52);\n"
                                 "color: rgb(255, 255, 255);")
        self.bmais.setObjectName("bmais")
        self.gridLayout.addWidget(self.bmais, 4, 3, 1, 1)
        self.b8 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b8.sizePolicy().hasHeightForWidth())
        self.b8.setSizePolicy(sizePolicy)
        self.b8.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b8.setFont(font)
        self.b8.setStyleSheet("background-color: rgb(52, 52, 52);\n"
                              "color: rgb(255, 255, 255);")
        self.b8.setObjectName("b8")
        self.gridLayout.addWidget(self.b8, 2, 1, 1, 1)
        self.basterisco = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.basterisco.sizePolicy().hasHeightForWidth())
        self.basterisco.setSizePolicy(sizePolicy)
        self.basterisco.setMaximumSize(QtCore.QSize(1677754, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.basterisco.setFont(font)
        self.basterisco.setStyleSheet("background-color: rgb(52, 52, 52);\n"
                                      "color: rgb(255, 255, 255);")
        self.basterisco.setObjectName("basterisco")
        self.gridLayout.addWidget(self.basterisco, 2, 3, 1, 1)
        self.frameTela = QtWidgets.QFrame(self.frame)
        self.frameTela.setStyleSheet("")
        self.frameTela.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTela.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTela.setObjectName("frameTela")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameTela)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Tela = QtWidgets.QLCDNumber(self.frameTela)
        self.Tela.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Tela.sizePolicy().hasHeightForWidth())
        self.Tela.setSizePolicy(sizePolicy)
        self.Tela.setMinimumSize(QtCore.QSize(300, 0))
        self.Tela.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Embassy BT")
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Tela.setFont(font)
        self.Tela.setStyleSheet("color: rgb(255, 255, 255);")
        self.Tela.setSmallDecimalPoint(True)
        self.Tela.setDigitCount(12)
        self.Tela.setProperty("value", 53105.0)
        self.Tela.setObjectName("Tela")
        self.verticalLayout_2.addWidget(self.Tela, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addWidget(self.frameTela, 0, 0, 1, 4)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        #! ACABOU A DEFINI��O DOS OBJETOS---------------------------------

        # ? FUN��ES--------------------------------------------------------

        self.screen2 = '0'
        self.screen1 = '0'
        self.aux = 1
        self.Tela.setProperty("value", "0")
        self.corpadrao = "background-color: rgb(52, 52, 52);\n""color: rgb(255, 255, 255);"
        self.corescolha = "background-color: rgb(52, 52, 100);\n""color: rgb(50, 200, 50);"
        self.operacao = 0

        self.bigual.clicked.connect(self.igual)
        self.bmais.clicked.connect(self.mais)
        self.bmenos.clicked.connect(self.menos)
        self.basterisco.clicked.connect(self.mult)
        self.bdiv.clicked.connect(self.div)
        self.b9.clicked.connect(lambda: self.addTela("9", self.aux))
        self.b8.clicked.connect(lambda: self.addTela("8", self.aux))
        self.b7.clicked.connect(lambda: self.addTela("7", self.aux))
        self.b6.clicked.connect(lambda: self.addTela("6", self.aux))
        self.b5.clicked.connect(lambda: self.addTela("5", self.aux))
        self.b4.clicked.connect(lambda: self.addTela("4", self.aux))
        self.b3.clicked.connect(lambda: self.addTela("3", self.aux))
        self.b2.clicked.connect(lambda: self.addTela("2", self.aux))
        self.b1.clicked.connect(lambda: self.addTela("1", self.aux))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def mais(self):
        self.operacao = "+"
        if self.aux == 1:
            self.aux = 2
        elif self.aux == 2:
            self.screen1 = self.screen2
            self.screen2 = "0"
        self.bmais.setStyleSheet(self.corescolha)

    def menos(self):
        self.operacao = "-"
        if self.aux == 1:
            self.aux = 2
        elif self.aux == 2:
            self.screen1 = self.screen2
            self.screen2 = "0"
        self.resetcolor()
        self.bmenos.setStyleSheet(self.corescolha)

    def mult(self):
        self.operacao = "*"
        if self.aux == 1:
            self.aux = 2
        elif self.aux == 2:
            self.screen1 = self.screen2
            self.screen2 = "0"
        self.resetcolor()
        self.basterisco.setStyleSheet(self.corescolha)

    def div(self):
        self.operacao = "/"
        if self.aux == 1:
            self.aux = 2
        elif self.aux == 2:
            self.screen2 = "0"
        self.resetcolor()
        self.bdiv.setStyleSheet(self.corescolha)

    def igual(self):
        if self.operacao == "+":
            self.resultado = int(self.screen1)+int(self.screen2)
        if self.operacao == "-":
            self.resultado = int(self.screen1)-int(self.screen2)
        if self.operacao == "*":
            self.resultado = int(self.screen1)*int(self.screen2)
        if self.operacao == "/":
            self.resultado = int(self.screen1)/int(self.screen2)
        self.atualizarTela(self.resultado)
        self.screen1 = self.resultado
        self.screen2 = '0'
        self.aux = 1
        self.resetcolor()
        self.operacao = 0

    def atualizarTela(self, numero):
        self.Tela.setProperty("value", numero)

    def addTela(self, numero, screen):
        if self.operacao == "":
            self.screen1 = 0

        if screen == 1:
            self.screen1 = str(self.screen1) + str(numero)
            self.atualizarTela(self.screen1)
        elif screen == 2:
            self.screen2 += (numero)
            self.atualizarTela(self.screen2)

    def resetcolor(self):
        self.bmais.setStyleSheet(self.corpadrao)
        self.bmenos.setStyleSheet(self.corpadrao)
        self.basterisco.setStyleSheet(self.corpadrao)
        self.bdiv.setStyleSheet(self.corpadrao)

        # ? END--------------------------------------------------------------

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bponto.setText(_translate("MainWindow", "."))
        self.bmenos.setText(_translate("MainWindow", "-"))
        self.b6.setText(_translate("MainWindow", "6"))
        self.bigual.setText(_translate("MainWindow", "="))
        self.b2.setText(_translate("MainWindow", "2"))
        self.bdiv.setText(_translate("MainWindow", "/"))
        self.b1.setText(_translate("MainWindow", "1"))
        self.b5.setText(_translate("MainWindow", "5"))
        self.b9.setText(_translate("MainWindow", "9"))
        self.b7.setText(_translate("MainWindow", "7"))
        self.b0.setText(_translate("MainWindow", "0"))
        self.b4.setText(_translate("MainWindow", "4"))
        self.b3.setText(_translate("MainWindow", "3"))
        self.bmais.setText(_translate("MainWindow", "+"))
        self.b8.setText(_translate("MainWindow", "8"))
        self.basterisco.setText(_translate("MainWindow", "*"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
